previews:
  generation: automatic
services:
  - type: web
    region: frankfurt
    name: sample-ruby-app
    plan: free
    env: ruby
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
