previews:
  generation: automatic
services:
  - type: web
    name: app1-frankfurt
    region: frankfurt
    plan: starter
    autoDeploy: false
    envVars:
      - key: REGION
        value: "Frankfurt"
    runtime: ruby
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
  - type: web
    name: app1-virginia
    region: virginia
    plan: starter
    autoDeploy: false
    envVars:
      - key: REGION
        value: "Virginia"
    runtime: ruby
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh

