previews:
  generation: automatic

projects:
  - name: sample-ruby-app-single-yaml
    environments:
      - name: production
        services:
          - type: web
            name: sample-ruby-app-new
            plan: free
            env: ruby
            autoDeploy: false
            envVars:
              - key: env
                value: production
            buildCommand: ./render-build.sh
            startCommand: ./render-start.sh
      - name: staging
        services:
          - type: web
            name: sample-ruby-app-new-staging-v2
            plan: free
            env: ruby
            envVars:
              - key: env
                value: staging
            buildCommand: ./render-build.sh
            startCommand: ./render-start.sh
