projects:
  - name: sample-ruby-app
    environments:
      - name: production
        services:
          - type: web
            name: sample-ruby-app-new
            plan: free
            env: ruby
            envVars:
              - key: env
                value: test
            buildCommand: ./render-build.sh; echo "buildCommand"
            startCommand: ./render-start.sh
