previews:
  generation: automatic

projects:
  - name: sample-ruby-app
    environments:
      - name: production
        services:
          - type: web
            name: sample-ruby-app-new
            plan: starter
            env: ruby
            envVars:
              - key: env
                value: test
            buildCommand: ./render-build.sh
            startCommand: ./render-start.sh
            preDeployCommand: ./render-predeploy.sh
            initialDeployHook: ./render-initialdeployhook.sh
